services:
  blog-admin:
    image: ghcr.io/shenlye/my-api:latest
    container_name: blog-admin
    ports:
      - "8088:3000"
    volumes:
      - ./data:/app/data
    environment:
      DATABASE_URL: /app/data/sqlite.db
      JWT_SECRET: your_jwt_secret_key
      DEFAULT_ADMIN_PASSWORD: admin123456
      ALLOWED_ORIGINS: http://localhost:5173
      PORT: 3000
    restart: always
